# Form implementation generated from reading ui file 'dlgSalir.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgSalir(object):
    def setupUi(self, dlgSalir):
        dlgSalir.setObjectName("dlgSalir")
        dlgSalir.resize(300, 200)
        dlgSalir.setMinimumSize(QtCore.QSize(300, 200))
        dlgSalir.setMaximumSize(QtCore.QSize(300, 200))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/taller.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        dlgSalir.setWindowIcon(icon)
        dlgSalir.setModal(True)
        self.ventanaSalir = QtWidgets.QDialogButtonBox(dlgSalir)
        self.ventanaSalir.setGeometry(QtCore.QRect(60, 140, 161, 32))
        self.ventanaSalir.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.ventanaSalir.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.ventanaSalir.setObjectName("ventanaSalir")
        self.lblImagenAviso = QtWidgets.QLabel(dlgSalir)
        self.lblImagenAviso.setGeometry(QtCore.QRect(110, 30, 81, 61))
        self.lblImagenAviso.setText("")
        self.lblImagenAviso.setPixmap(QtGui.QPixmap("img/AVISO.png"))
        self.lblImagenAviso.setScaledContents(True)
        self.lblImagenAviso.setObjectName("lblImagenAviso")
        self.lblPregunta = QtWidgets.QLabel(dlgSalir)
        self.lblPregunta.setGeometry(QtCore.QRect(110, 100, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lblPregunta.setFont(font)
        self.lblPregunta.setObjectName("lblPregunta")

        self.retranslateUi(dlgSalir)
        self.ventanaSalir.accepted.connect(dlgSalir.accept) # type: ignore
        self.ventanaSalir.rejected.connect(dlgSalir.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dlgSalir)

    def retranslateUi(self, dlgSalir):
        _translate = QtCore.QCoreApplication.translate
        dlgSalir.setWindowTitle(_translate("dlgSalir", "Salir"))
        self.lblPregunta.setText(_translate("dlgSalir", "¿Desea salir?"))
