# Form implementation generated from reading ui file 'ventCalendar.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ventCalendar(object):
    def setupUi(self, ventCalendar):
        ventCalendar.setObjectName("ventCalendar")
        ventCalendar.resize(240, 175)
        ventCalendar.setMinimumSize(QtCore.QSize(240, 175))
        ventCalendar.setMaximumSize(QtCore.QSize(240, 175))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/calendar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ventCalendar.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(ventCalendar)
        self.centralwidget.setObjectName("centralwidget")
        self.calendar = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendar.setGeometry(QtCore.QRect(0, 0, 240, 170))
        self.calendar.setMinimumSize(QtCore.QSize(240, 170))
        self.calendar.setMaximumSize(QtCore.QSize(240, 170))
        self.calendar.setObjectName("calendar")
        ventCalendar.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ventCalendar)
        self.statusbar.setObjectName("statusbar")
        ventCalendar.setStatusBar(self.statusbar)

        self.retranslateUi(ventCalendar)
        QtCore.QMetaObject.connectSlotsByName(ventCalendar)

    def retranslateUi(self, ventCalendar):
        _translate = QtCore.QCoreApplication.translate
        ventCalendar.setWindowTitle(_translate("ventCalendar", "Calendario"))
